package com.s63d.domain.scraper

val cities = listOf("Vienna",
        "Graz",
        "Linz",
        "Salzburg",
        "Innsbruck",
        "Klagenfurt",
        "Villach",
        "Wels",
        "Sankt Pölten",
        "Dornbirn",
        "Wiener Neustadt",
        "Steyr",
        "Feldkirch",
        "Bregenz",
        "Leonding",
        "Klosterneuburg",
        "Baden bei Wien",
        "Wolfsberg",
        "Leoben",
        "Krems",
        "Traun",
        "Amstetten",
        "Lustenau",
        "Kapfenberg",
        "Mödling",
        "Hallein",
        "Kufstein",
        "Traiskirchen",
        "Schwechat",
        "Braunau am Inn",
        "Stockerau",
        "Saalfelden",
        "Ansfelden",
        "Tulln",
        "Hohenems",
        "Spittal an der Drau",
        "Telfs",
        "Ternitz",
        "Perchtoldsdorf",
        "Feldkirchen",
        "Bludenz",
        "Bad Ischl",
        "Eisenstadt",
        "Schwaz",
        "Hall in Tirol",
        "Gmunden",
        "Wörgl",
        "Wals-Siezenheim",
        "Marchtrenk",
        "Bruck an der Mur",
        "Sankt Veit an der Glan",
        "Korneuburg",
        "Neunkirchen",
        "Hard",
        "Vöcklabruck",
        "Lienz",
        "Rankweil",
        "Hollabrunn",
        "Enns",
        "Brunn am Gebirge",
        "Ried im Innkreis",
        "Bad Vöslau",
        "Waidhofen",
        "Knittelfeld",
        "Trofaiach",
        "Mistelbach",
        "Zwettl",
        "Völkermarkt",
        "Götzis",
        "Sankt Johann im Pongau",
        "Gänserndorf",
        "Gerasdorf bei Wien",
        "Ebreichsdorf",
        "Bischofshofen",
        "Groß-Enzersdorf",
        "Seekirchen am Wallersee",
        "Sankt Andrä")